spring:
  datasource:
    url: jdbc:mysql://localhost:3307/prueba?useSSL=false
    username: root
    password: pass1234
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
